// Generates src/renderer/src/assets/tiles.generated.ts: the SVG path data of every glyph in the tile
// catalog, taken from the "fill" weight of @phosphor-icons/core.
//
//   node scripts/generate-tiles.cjs           rewrite the generated file
//   node scripts/generate-tiles.cjs --check   fail when the committed file is out of date
//
// The 150 glyphs are looked up by name at run time (an entry icon is stored as `tile:<glyph>:<colour>`),
// so they cannot be static imports of 150 React components. Embedding the path data keeps the main
// bundle small (about 65 KB) and makes the glyph set independent of the icon package version.
// Re-run the script after editing the catalog or upgrading @phosphor-icons/core, and commit the result.
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const catalogPath = path.join(
  root,
  'src',
  'renderer',
  'src',
  'assets',
  'tile-catalog.json'
)
const outputPath = path.join(
  root,
  'src',
  'renderer',
  'src',
  'assets',
  'tiles.generated.ts'
)
const fillDir = path.join(
  root,
  'node_modules',
  '@phosphor-icons',
  'core',
  'assets',
  'fill'
)
const VIEW_BOX = '0 0 256 256'

function glyphNames(catalog) {
  const names = []
  for (const category of catalog.categories) {
    for (const glyph of category.glyphs) {
      if (names.includes(glyph.phosphor)) {
        throw new Error(`Glyph listed twice in the catalog: ${glyph.phosphor}`)
      }
      names.push(glyph.phosphor)
    }
  }
  return names
}

// Returns the `d` attribute of every <path> in a Phosphor fill SVG. Anything else in the file (another
// element type, a different view box) is an error: the renderer only knows how to draw plain paths.
function readPaths(name) {
  const file = path.join(fillDir, `${name}-fill.svg`)
  if (!fs.existsSync(file)) {
    throw new Error(`Missing Phosphor fill glyph: ${file}`)
  }
  const svg = fs.readFileSync(file, 'utf8')
  const open = svg.match(/^<svg\b([^>]*)>/)
  if (!open || !open[1].includes(`viewBox="${VIEW_BOX}"`)) {
    throw new Error(`${name}: expected viewBox "${VIEW_BOX}"`)
  }
  const body = svg.slice(open[0].length).replace(/<\/svg>\s*$/, '')
  const elements = body.match(/<[a-zA-Z][^>]*>/g) ?? []
  const paths = []
  for (const element of elements) {
    const match = element.match(/^<path d="([^"]+)"\s*\/>$/)
    if (!match) {
      throw new Error(`${name}: unsupported SVG element ${element}`)
    }
    paths.push(match[1])
  }
  if (paths.length === 0) {
    throw new Error(`${name}: no path found`)
  }
  return paths
}

function generateTilesSource() {
  const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'))
  const lines = [
    '// Generated by scripts/generate-tiles.cjs from src/renderer/src/assets/tile-catalog.json and the',
    '// "fill" weight of @phosphor-icons/core (MIT, see THIRD-PARTY-NOTICES.md). Do not edit by hand:',
    '// run `node scripts/generate-tiles.cjs` instead.',
    '',
    `export const TILE_VIEW_BOX = '${VIEW_BOX}'`,
    '',
    '/** Glyph name (as in the catalog) -> the `d` attribute of each path of its filled drawing. */',
    'export const TILE_GLYPHS: Readonly<Record<string, readonly string[]>> = {',
  ]
  for (const name of glyphNames(catalog)) {
    lines.push(`  '${name}': [`)
    for (const d of readPaths(name)) {
      lines.push(`    '${d}',`)
    }
    lines.push('  ],')
  }
  lines.push('}', '')
  return lines.join('\n')
}

module.exports = { generateTilesSource, outputPath }

if (require.main === module) {
  const source = generateTilesSource()
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(outputPath)
      ? fs.readFileSync(outputPath, 'utf8')
      : ''
    if (current !== source) {
      console.error(
        'tiles.generated.ts is out of date: run `node scripts/generate-tiles.cjs`.'
      )
      process.exit(1)
    }
    console.log('tiles.generated.ts is up to date.')
  } else {
    fs.writeFileSync(outputPath, source)
    console.log(`Wrote ${path.relative(root, outputPath)}`)
  }
}
