import fs from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import zlib from 'node:zlib'

import { describe, expect, it } from 'vitest'

/**
 * The application icon files are generated by scripts/generate-icons.ps1 from the two SVG sources in
 * src/renderer/src/assets. These tests decode the committed binaries and compare them with the geometry and
 * colours declared in those SVGs, so a stale or wrongly generated icon is caught without opening an image.
 */
const projectDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  '..'
)
const assetDir = path.join(projectDir, 'src/renderer/src/assets')
const iconDir = path.join(projectDir, 'resources/icons')
const SIZES = [16, 20, 24, 32, 40, 48, 64, 128, 256]
/** Sizes up to this use marubako-small.svg (larger dot, art closer to the canvas edge). */
const SMALL_ART_MAX_SIZE = 24
const PNG_SIGNATURE = Buffer.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
])

type Rgb = [number, number, number]
type Rgba = [number, number, number, number]

interface Png {
  width: number
  height: number
  bitDepth: number
  colorType: number
  rgba: Uint8Array
}

/** Array read that satisfies noUncheckedIndexedAccess and fails loudly when the index is out of range. */
function at(values: ArrayLike<number>, index: number): number {
  const value = values[index]
  if (value === undefined) throw new Error(`Index ${index} is out of range`)
  return value
}

/** Minimal PNG decoder for the 8-bit RGBA / RGB, non-interlaced files the generator writes. */
function decodePng(file: Buffer): Png {
  if (!file.subarray(0, 8).equals(PNG_SIGNATURE))
    throw new Error('Not a PNG file')
  let offset = 8
  let width = 0
  let height = 0
  let bitDepth = 0
  let colorType = 0
  let interlace = 0
  const compressed: Buffer[] = []
  while (offset < file.length) {
    const length = file.readUInt32BE(offset)
    const type = file.toString('ascii', offset + 4, offset + 8)
    const data = file.subarray(offset + 8, offset + 8 + length)
    if (type === 'IHDR') {
      width = data.readUInt32BE(0)
      height = data.readUInt32BE(4)
      bitDepth = data.readUInt8(8)
      colorType = data.readUInt8(9)
      interlace = data.readUInt8(12)
    } else if (type === 'IDAT') compressed.push(data)
    else if (type === 'IEND') break
    offset += 12 + length
  }
  if (bitDepth !== 8 || interlace !== 0 || ![2, 6].includes(colorType))
    throw new Error(`Unsupported PNG layout ${bitDepth}/${colorType}`)
  const bytesPerPixel = colorType === 6 ? 4 : 3
  const stride = width * bytesPerPixel
  const raw = zlib.inflateSync(Buffer.concat(compressed))
  const rgba = new Uint8Array(width * height * 4)
  let previous = new Uint8Array(stride)
  for (let y = 0; y < height; y++) {
    const filter = raw.readUInt8(y * (stride + 1))
    const line = Uint8Array.from(
      raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1))
    )
    for (let i = 0; i < stride; i++) {
      const left = i >= bytesPerPixel ? at(line, i - bytesPerPixel) : 0
      const up = at(previous, i)
      const upLeft = i >= bytesPerPixel ? at(previous, i - bytesPerPixel) : 0
      let predictor = 0
      if (filter === 1) predictor = left
      else if (filter === 2) predictor = up
      else if (filter === 3) predictor = (left + up) >> 1
      else if (filter === 4) {
        const estimate = left + up - upLeft
        const distanceLeft = Math.abs(estimate - left)
        const distanceUp = Math.abs(estimate - up)
        const distanceUpLeft = Math.abs(estimate - upLeft)
        predictor =
          distanceLeft <= distanceUp && distanceLeft <= distanceUpLeft
            ? left
            : distanceUp <= distanceUpLeft
              ? up
              : upLeft
      }
      line[i] = (at(line, i) + predictor) & 255
    }
    for (let x = 0; x < width; x++) {
      const target = (y * width + x) * 4
      rgba[target] = at(line, x * bytesPerPixel)
      rgba[target + 1] = at(line, x * bytesPerPixel + 1)
      rgba[target + 2] = at(line, x * bytesPerPixel + 2)
      rgba[target + 3] =
        bytesPerPixel === 4 ? at(line, x * bytesPerPixel + 3) : 255
    }
    previous = line
  }
  return { width, height, bitDepth, colorType, rgba }
}

function readIconPng(size: number): { bytes: Buffer; png: Png } {
  const bytes = fs.readFileSync(path.join(iconDir, `marubako-${size}.png`))
  return { bytes, png: decodePng(bytes) }
}

function pixel(png: Png, x: number, y: number): Rgba {
  const offset = (y * png.width + x) * 4
  return [
    at(png.rgba, offset),
    at(png.rgba, offset + 1),
    at(png.rgba, offset + 2),
    at(png.rgba, offset + 3),
  ]
}

/** The pixel covering a point given in the 256 x 256 viewBox of the SVG sources. */
function pixelAt(png: Png, viewBoxX: number, viewBoxY: number): Rgba {
  return pixel(
    png,
    Math.floor((viewBoxX / 256) * png.width),
    Math.floor((viewBoxY / 256) * png.height)
  )
}

interface IconArt {
  svg: string
  start: Rgb
  end: Rgb
  gradient: { x1: number; y1: number; x2: number; y2: number }
  dot: { cx: number; cy: number; r: number }
}

function hexToRgb(hex: string): Rgb {
  const channel = (index: number) => parseInt(hex.slice(index, index + 2), 16)
  return [channel(1), channel(3), channel(5)]
}

function readArt(fileName: string): IconArt {
  const svg = fs.readFileSync(path.join(assetDir, fileName), 'utf8')
  // A missing attribute or stop becomes NaN / black so the assertions below fail one by one instead of the file crashing.
  const attribute = (tag: string, name: string): number =>
    Number(
      new RegExp(`<${tag}\\b[^>]*\\s${name}="([^"]+)"`).exec(svg)?.[1] ?? 'NaN'
    )
  const stops = [
    ...svg.matchAll(/<stop offset="[01]" stop-color="(#[0-9A-Fa-f]{6})"/g),
  ].map((match) => hexToRgb(match[1] ?? '#000000'))
  return {
    svg,
    start: stops[0] ?? [0, 0, 0],
    end: stops[1] ?? [0, 0, 0],
    gradient: {
      x1: attribute('linearGradient', 'x1'),
      y1: attribute('linearGradient', 'y1'),
      x2: attribute('linearGradient', 'x2'),
      y2: attribute('linearGradient', 'y2'),
    },
    dot: {
      cx: attribute('circle', 'cx'),
      cy: attribute('circle', 'cy'),
      r: attribute('circle', 'r'),
    },
  }
}

const mainArt = readArt('marubako.svg')
const smallArt = readArt('marubako-small.svg')

function artFor(size: number): IconArt {
  return size <= SMALL_ART_MAX_SIZE ? smallArt : mainArt
}

/** The SVG's userSpaceOnUse gradient colour at a viewBox point (stops are clamped beyond the vector). */
function gradientColorAt(art: IconArt, x: number, y: number): Rgb {
  const { x1, y1, x2, y2 } = art.gradient
  const dx = x2 - x1
  const dy = y2 - y1
  const t = Math.min(
    1,
    Math.max(0, ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy))
  )
  const mix = (from: number, to: number) => from + (to - from) * t
  return [
    mix(art.start[0], art.end[0]),
    mix(art.start[1], art.end[1]),
    mix(art.start[2], art.end[2]),
  ]
}

function expectNear(actual: Rgb, expected: Rgb, tolerance: number) {
  for (const index of [0, 1, 2])
    expect(
      Math.abs(at(actual, index) - at(expected, index))
    ).toBeLessThanOrEqual(tolerance)
}

function luminance([r, g, b]: Rgb): number {
  const linear = (channel: number) => {
    const value = channel / 255
    return value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4
  }
  return 0.2126 * linear(r) + 0.7152 * linear(g) + 0.0722 * linear(b)
}

function contrastRatio(a: Rgb, b: Rgb): number {
  const first = luminance(a)
  const second = luminance(b)
  return (Math.max(first, second) + 0.05) / (Math.min(first, second) + 0.05)
}

function rgbOf([r, g, b]: Rgba): Rgb {
  return [r, g, b]
}

describe('application icon sources', () => {
  it('uses the violet gradient #9A85FF to #5544DA in both SVGs, with the same dot position', () => {
    for (const art of [mainArt, smallArt]) {
      expect(art.start).toEqual(hexToRgb('#9A85FF'))
      expect(art.end).toEqual(hexToRgb('#5544DA'))
      expect(art.dot.cx).toBe(104)
      expect(art.dot.cy).toBe(152)
    }
    expect(smallArt.dot.r).toBeGreaterThan(mainArt.dot.r)
  })

  it('draws a rounded square with one quarter-circle corner and a dot, not the old bolt polygon', () => {
    expect(mainArt.svg).not.toContain('<polygon')
    expect(mainArt.svg).toContain('A104 104 0 0 1 24 128')
    expect(mainArt.svg).toContain('<circle')
    expect(smallArt.svg).not.toContain('<polygon')
    expect(smallArt.svg).toContain('<circle')
  })

  it('leaves no trace of the old bolt art in the renderer assets or resources', () => {
    const files = [assetDir, iconDir].flatMap((directory) =>
      fs
        .readdirSync(directory)
        .filter((name) => name.endsWith('.svg'))
        .map((name) => path.join(directory, name))
    )
    expect(files.length).toBeGreaterThan(0)
    for (const file of files) {
      const text = fs.readFileSync(file, 'utf8')
      expect(text, file).not.toMatch(/<polygon|146,42|9B78FF|5656D8/i)
    }
  })
})

describe('application icon PNGs', () => {
  it.each(SIZES)(
    'marubako-%i.png is a square 32-bit PNG of that size',
    (size) => {
      const { png } = readIconPng(size)
      expect(png.width).toBe(size)
      expect(png.height).toBe(size)
      expect(png.bitDepth).toBe(8)
      expect(png.colorType).toBe(6)
    }
  )

  it.each(SIZES)(
    'marubako-%i.png has transparent corners and a transparent bottom-left quarter-circle cut',
    (size) => {
      const { png } = readIconPng(size)
      for (const [x, y] of [
        [0, 0],
        [size - 1, 0],
        [0, size - 1],
        [size - 1, size - 1],
      ] as const)
        expect(pixel(png, x, y)[3]).toBe(0)
      // Inside the 256 box but outside the big bottom-left arc (r 104 or 112 around 128,128) ...
      expect(pixelAt(png, 32, 224)[3]).toBe(0)
      // ... while the arc's inside is solid, as is the top-right corner region that only has a small radius.
      expect(pixelAt(png, 72, 184)[3]).toBe(255)
      expect(pixelAt(png, 200, 56)[3]).toBe(255)
    }
  )

  it.each(SIZES)(
    'marubako-%i.png fills the gradient from violet #9A85FF at the top left to #5544DA at the bottom right',
    (size) => {
      const { png } = readIconPng(size)
      const art = artFor(size)
      for (const [x, y] of [
        [56, 40],
        [100, 60],
        [200, 216],
        [210, 150],
      ] as const) {
        const sample = pixelAt(png, x, y)
        expect(sample[3]).toBe(255)
        expectNear(rgbOf(sample), gradientColorAt(art, x, y), 12)
      }
      const top = pixelAt(png, 56, 40)
      const bottom = pixelAt(png, 200, 216)
      expect(top[2]).toBeGreaterThan(240)
      expect(top[0]).toBeGreaterThan(bottom[0] + 40)
      expect(bottom[0]).toBeLessThan(110)
    }
  )

  it.each(SIZES)(
    'marubako-%i.png has a white dot left of centre and below it, clearly separated from the fill',
    (size) => {
      const { png } = readIconPng(size)
      const { cx, cy, r } = artFor(size).dot
      expect(pixelAt(png, cx, cy)).toEqual([255, 255, 255, 255])
      // The dot sits lower left: the mirrored point upper right is plain fill, not white.
      expect(pixelAt(png, 256 - cx, 256 - cy)[0]).toBeLessThan(200)
      // Left and right of the dot, one pixel-width clear of its edge, the pixels are fill, not white.
      const gap = Math.max(20, 256 / size + 4)
      const left = pixelAt(png, cx - r - gap, cy)
      const right = pixelAt(png, cx + r + gap, cy)
      expect(left[3]).toBe(255)
      expect(right[3]).toBe(255)
      expect(left[0]).toBeLessThan(200)
      expect(right[0]).toBeLessThan(200)
      // The dot keeps a clear contrast against the fill next to it (3:1 is the WCAG minimum for graphics).
      expect(contrastRatio([255, 255, 255], rgbOf(left))).toBeGreaterThan(3)
      expect(contrastRatio([255, 255, 255], rgbOf(right))).toBeGreaterThan(3)
    }
  )

  it('keeps the 16 px dot legible: a solid white block of several pixels', () => {
    const { png } = readIconPng(16)
    let white = 0
    for (let y = 0; y < 16; y++)
      for (let x = 0; x < 16; x++) {
        const [r, g, b, a] = pixel(png, x, y)
        if (r >= 250 && g >= 250 && b >= 250 && a === 255) white++
      }
    // The dot covers about 24 px² at 16 px; interior pixels without edge blending are well over a dozen.
    expect(white).toBeGreaterThanOrEqual(12)
  })

  it.each(SIZES)(
    'marubako-%i.png covers the art box of its SVG: main art 24-232, small art 16-240',
    (size) => {
      const { png } = readIconPng(size)
      const [low, high] = size <= SMALL_ART_MAX_SIZE ? [16, 240] : [24, 232]
      let minX = size
      let minY = size
      let maxX = -1
      let maxY = -1
      // Alpha of 1-2 on a boundary pixel is anti-aliasing noise (and the small SVG's top-left arc rises 0.7 units
      // above its top edge), so only visible pixels count.
      for (let y = 0; y < size; y++)
        for (let x = 0; x < size; x++)
          if (pixel(png, x, y)[3] >= 8) {
            minX = Math.min(minX, x)
            minY = Math.min(minY, y)
            maxX = Math.max(maxX, x)
            maxY = Math.max(maxY, y)
          }
      const first = Math.floor((low / 256) * size)
      const last = Math.ceil((high / 256) * size) - 1
      expect([minX, minY, maxX, maxY]).toEqual([first, first, last, last])
    }
  )
})

describe('application icon ICO files', () => {
  it.each(['icon.ico', 'icon-256.ico'])(
    '%s lists the nine sizes and embeds the same PNG frames as resources/icons',
    (fileName) => {
      const ico = fs.readFileSync(
        path.join(projectDir, 'resources/icons', fileName)
      )
      expect(ico.readUInt16LE(0)).toBe(0)
      expect(ico.readUInt16LE(2)).toBe(1)
      expect(ico.readUInt16LE(4)).toBe(SIZES.length)
      SIZES.forEach((size, index) => {
        const entry = 6 + index * 16
        // The directory stores 256 as 0.
        const stored = size === 256 ? 0 : size
        expect(ico.readUInt8(entry)).toBe(stored)
        expect(ico.readUInt8(entry + 1)).toBe(stored)
        expect(ico.readUInt16LE(entry + 4)).toBe(1)
        expect(ico.readUInt16LE(entry + 6)).toBe(32)
        const length = ico.readUInt32LE(entry + 8)
        const offset = ico.readUInt32LE(entry + 12)
        const frame = ico.subarray(offset, offset + length)
        expect(frame.length).toBe(length)
        const decoded = decodePng(Buffer.from(frame))
        expect([decoded.width, decoded.height]).toEqual([size, size])
        expect(frame.equals(readIconPng(size).bytes)).toBe(true)
      })
    }
  )

  it('keeps icon.ico and icon-256.ico identical, the files electron-builder, the window and the tray point at', () => {
    const icons = path.join(projectDir, 'resources/icons')
    expect(
      fs
        .readFileSync(path.join(icons, 'icon.ico'))
        .equals(fs.readFileSync(path.join(icons, 'icon-256.ico')))
    ).toBe(true)
    const config = createRequire(import.meta.url)(
      path.join(projectDir, 'electron-builder.config.cjs')
    ) as { win: { icon: string }; files: string[] }
    expect(fs.existsSync(path.join(projectDir, config.win.icon))).toBe(true)
    expect(config.win.icon).toBe('resources/icons/icon-256.ico')
    expect(config.files).toEqual(
      expect.arrayContaining(['resources/icons/*.png', 'resources/icons/*.ico'])
    )
    const windowManager = fs.readFileSync(
      path.join(projectDir, 'src/main/window-manager.ts'),
      'utf8'
    )
    expect(windowManager).toContain("'resources', 'icons', 'icon.ico'")
    // Nothing of the kind is left in the project root.
    expect(fs.existsSync(path.join(projectDir, 'icon.ico'))).toBe(false)
  })

  it('ships every PNG size the tray asks for', () => {
    const tray = fs.readFileSync(
      path.join(projectDir, 'src/main/tray.ts'),
      'utf8'
    )
    const list = /for \(const size of \[([\d,\s]+)\]\)/.exec(tray)
    expect(list).not.toBeNull()
    const requested = (list?.[1] ?? '').split(',').map((value) => Number(value))
    expect(requested.length).toBeGreaterThan(0)
    for (const size of requested) expect(SIZES).toContain(size)
  })
})
